apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-0001
  namespace: demo
  labels:
    pvc: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-0002
  namespace: demo
  labels:
    pvc: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi