apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  namespace: demo
  labels:
    app: es-discovery
spec:
  selector:
    app: es
  ports:
  - name: transport
    port: 9300
    protocol: TCP