apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-edp
  namespace: data-cube
subsets:
  - address:
    - ip: 10.8.177.26
    ports:
    - port: 9190
  - address:
    - ip: 10.8.177.27
    ports:
    - port: 9190
  - address:
    - ip: 10.8.177.28
    ports:
    - port: 9190
  - address:
    - ip: 10.8.177.29
    ports:
    - port: 9190
  - address:
    - ip: 10.8.177.30
    ports:
    - port: 9190