apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-20g-01
  labels:
    use: nexus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  glusterfs:
    endpoints: "glusterfs-edp"
    path: "pv-20g-01"
    readOnly: false