apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dubbo-monitor-dep
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-monitor
  template:
    metadata:
      namespace: demo
      labels:
        app: dubbo-monitor
    spec:
      containers:
      - name: dubbo-monitor
        image: alleyz.com:5000/dubbo-monitor:2.5.8
        imagePullPolicy: Always
        env:
          - name: ZK_HOST
            value: "zk-0.zk-svc.demo.svc.cluster.local:2181\\/\\/zk-1.zk-svc.demo.svc.cluster.local:2181\\/\\/zk-2.zk-svc.demo.svc.cluster.local:2181"
        ports:
        - containerPort: 8080