apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-10g-sonar
  namespace: data-cube
  labels:
    pvc: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      use: sonar