apiVersion: v1
kind: Service
metadata:
  name: sonarqube-svc
  namespace: data-cube
  labels:
    role: sonarqube-svc
spec:
  selector:
    app: sonarqube
  type: NodePort
  ports:
  - name: web
    port: 9000
    nodePort: 32090
    protocol: TCP