apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dir-zk-0
  namespace: demo
  labels:
    pvc: zk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dir-zk-1
  namespace: demo
  labels:
    pvc: zk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dir-zk-2
  namespace: demo
  labels:
    pvc: zk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dir-zk-3
  namespace: demo
  labels:
    pvc: zk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dir-zk-4
  namespace: demo
  labels:
    pvc: zk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi