apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
spec:
  replicas: 1
  selector:
    redis-sentinel: "true"
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
    spec:
      containers:
      - name: sentinel
        image: alleyz.com:5000/redis:3.2.11-alpine
        imagePullPolicy: IfNotPresent
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379