apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: demo
  name: es-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargrtRef:
    kind: Deployment
    name: es-dep
  targetCPUUtilizationPercentage: 80


  ----

  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: slow
  provisioner: kubernetes.io/glusterfs
  parameters:
    resturl: "http://hd-29:8081"
    clusterid: "1zdsf0snv8dn86dgaz900"
    restaruthenabled: "true"
    secretNamespace: "demo"
    gidMin: "40000"
    gidMax: "50000"
    volumetype: "replicate:3"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-0002
  namespace: demo
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      containers:
      - name: hello
        image: busybox
        args:
        - /bin/sh
        - -c
        - date; echo Hello