apiVersion: v1
kind: Service
metadata:
  name: es-svc
  namespace: demo
  labels:
    app: es-svc
spec:
  selector:
    app: es
  type: NodePort
  ports:
  - name: http
    port: 9200
    nodePort: 32000
    protocol: TCP