server:
    port: 37605
    context-path: /api-user/
logging:
    level:
        org.spring*: INFO
        com.alleyz.k8s: info
    file: api-user.log
spring:
  datasource:
      name: test
      ###武汉
      ## url: jdbc:oracle:thin:@172.16.52.3:1521:orcl
      ###北京
      url: %jdbc_url%
      username: %db_name%
      password: %db_password%
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      filters: config,stat
      maxActive: 5
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  dubbo:
    application: api-user
    protocol:
      name: dubbo
      port: 20880
#      host: 10.8.8.13
    registry:
      address: zookeeper://%zk_host%
    scan: com.alleyz.k8s.svc.user.service
    module:
      name: user-svc
      version: 10
    monitor:
      protocol: registry