apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skywalking-web-dep
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-web
  template:
    metadata:
      namespace: demo
      name: skywalking-web
      labels:
        app: skywalking-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - skywalking-web
            topologyKey: kubernetes.io/hostname
      containers:
      - name: skywalking-web
        image: alleyz.com:5000/skywalking-web:3.6
        imagePullPolicy: Always
        env:
          - name: COLLECTOR_SVC
            value: "skywalking-collector-svc:30100"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "500m"
        volumeMounts:
          - mountPath: /usr/local/skywalking-web/logs
            name: tmp-log
      nodeSelector:
        type: phy
      volumes:
        - name: tmp-log
          emptyDir: {}