apiVersion: v1
kind: Service
metadata:
  name: skywalking-web-svc
  namespace: demo
  labels:
    app: skywalking-web-svc
spec:
  selector:
    app: skywalking-web
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32080
    name: http