apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-30g-nexus
  namespace: data-cube
  labels:
    pvc: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      use: nexus