apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: data-cube
  labels:
    role: nexus-svc
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - name: http
    port: 8081
    nodePort: 32081
    protocol: HTTP