apiVersion: v1
kind: Service
metadata:
  name: skywalking-collector-svc
  namespace: demo
  labels:
    app: skywalking-collector-svc
spec:
  selector:
    app: skywalking-collector
  type: NodePort
  ports:
  - name: naming
    port: 10800
    nodePort: 30100
    protocol: TCP
  - name: grpc
    port: 11800
    nodePort: 30101
    protocol: TCP
  - name: jetty
    port: 12800
    nodePort: 30102
    protocol: TCP
