apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skywalking-collector-dep
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-collector
  template:
    metadata:
      namespace: demo
      name: skywalking-collector
      labels:
        app: skywalking-collector
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - skywalking-collector
            topologyKey: kubernetes.io/hostname
      containers:
      - name: skywalking-collector
        image: alleyz.com:5000/skywalking-collector:3.6
        imagePullPolicy: Always
        env:
          - name: ZK_HOST
            value: "zk-0.zk-svc.demo.svc.cluster.local:2181,zk-1.zk-svc.demo.svc.cluster.local:2181,zk-2.zk-svc.demo.svc.cluster.local:2181"
          - name: ES_CLUSTER_NAME
            value: "k8s-es"
          - name: ES_CLUSTER_NODE
            value: "es-discovery:9300"
        ports:
        - containerPort: 10800
          name: naming
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: jetty
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "500m"
        volumeMounts:
          - mountPath: /usr/local/skywalking-collector/logs
            name: tmp-log
      nodeSelector:
        type: phy
      volumes:
        - name: tmp-log
          emptyDir: {}