apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
  namespace: data-cube
spec:
  replicas: 1
  selector:
    redis-sentinel: "true"
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
      namespace: data-cube
    spec:
      containers:
      - name: sentinel
        image: data-cube.com:5000/hollycrm/redis-sentinel:3.2.11
        imagePullPolicy: Always
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379